mod border_material;
mod disconnected_fronts;
mod expansion_assignment;
mod expansion_processing;
mod game_update;
mod gpu;
mod gpu_orchestrator;
mod map_renderer;
mod perf_ui;
mod player_elimination;
mod player_info;
mod setup;

pub use border_material::BorderMaterial;
pub use gpu::{ExpansionWorker, sync_board_to_gpu};
pub use gpu_orchestrator::{gpu_orchestrator, AdjacencyMatrix, GpuOrchestratorTime};
pub use map_renderer::setup_map_texture;
pub use perf_ui::{setup_gpu_perf_ui, PerfUiEntryGpuTime};
pub use player_info::update_player_info;
pub use setup::setup;
